# https://goreleaser.com/customization/build/
builds:
  - goos:
      - linux
      - windows
      - darwin
    gcflags:
      - -trimpath
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
